version: '3.4'

services:
  client:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: Frontend/client
      dockerfile: Dockerfile
      args:
        - REACT_APP_NAME=Ignition
    environment:
      - REACT_APP_NAME=Ignition
    ports:
      - 5040:80
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: Backend
      dockerfile: WebAPI/Dockerfile
    environment:
     - ASPNETCORE_URLS=https://*:443;http://*:80
     - ASPNETCORE_Kestrel__Certificates__Default__Password=defaultPassword
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/usr/local/share/ca-certificates/ignition.pfx
    ports:
     - 5055:80
     - 5051:443